version: '3'
services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=Etc/UTC
      - TZ=Asia/Tokyo
    volumes:
      - ./config:/config
      # - /path/to/log:/var/log #optional
      - ./log:/var/log
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped

# ベース
# https://docs.linuxserver.io/images/docker-syslog-ng/
